### ISSUE TITLE
dependencies file

### ISSUE THREAD

**Issue by root-intruder** [ResurrectionRemix-Devices/device_xiaomi_sdm660-common#1]
I'm currently trying to build whyred myself and recognized that the file "lineage.dependencies" is never read and therefore no dependencies resolved.

The roomservice ./vendor/rr/build/tools/roomservice.py only searches for rr.dependencies!

So shouldn't you rename the file!? Or am I missing something?

Thanks!

**Comment by OdSazib** [comment]
You are right, I am not building rr for a long time and never used jenkins. Hence I did not know
